# Generated by Django 5.2 on 2025-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_email_student_course_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.ManyToManyField(related_name='user', to='app.roll'),
        ),
    ]
