# Generated by Django 5.2 on 2025-04-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_roll_alter_student_subject_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.roll'),
            preserve_default=False,
        ),
    ]
